services:
  - type: web
    name: app-sg-phone
    env: node
    plan: free
    buildCommand: npm install && npm run build:css
    startCommand: node scripts/start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: SESSION_TIMEOUT
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
    autoDeploy: true
    branch: main
    staticPublishPath: public
